### ISSUE TITLE
[Feat]make Webserv Run()

### ISSUE THREAD

**Issue by jwo1024** [brixxt27/webserv#11]
Webserv 클래스에서 kevent를 포함한 main loop 함수 Run() 을 만들고자함.
필요한 서브 함수들
- MakeEvent() → chage_event() // AddEvent() ?
- `bool IsErrorFlags();`
- `bool IsReadEvent();`
- `bool IsWriteEvent();`
- `iterator WhichSocket(begin, end)` // 서버 한번, 클라이언트 한번
- listen(socket) socket && readevent ()
    - accept
    - 
- client socket && readevent()
- client socket && writeevent()

**Comment by brixxt27** [comment]
Run() 의 기능을 구체화하여 이슈 생성 필요
