### ISSUE TITLE
[Feat] ```void *udata```을 활용한 kevent 루프 내의 socket 판별 루프 제거 고려

### ISSUE THREAD

**Issue by jwo1024** [brixxt27/webserv#26]
## Description
```void *udata```을 활용한 kevent 루프 내의 (어떤 socket에서 일어난 이벤트인지 판별하는)socket 판별 루프 제거 방법 고려
> udata 에 Server 혹은 Client 클래스의 포인터를 넣어, 
> 기존의 이벤트 발생시 어떤 소켓에 해당하는지 판별하는 루프문을 제거하고 바로 접근 가능하도록 만들고자 함. 
> 후에 추가적인 정보(response만드는 진행 단계 등) 을 빠르게 파악하는데에도 도움을 줄 것으로 생각됨.

## To do
- ```class SocketHandler``` 순수 추상 클래스 추가
     멤버 변수로 ```class Socket``` 을 가짐
- Server 클래스와 Client 클래스가 SocketHandler 를 상속받도록 함
    기존에 멤버 변수로 가지고 있던 ```class Socket```은 ```class SocketHandler```의 것을 상속받아 사용하도록 함
    ```class Server : protected SocketHandler``` 
    ```class Client : protected SocketHandler```
-  defines.hpp에  ```enum SocketHandlerType { kServer, kClient };``` 추가
    class Webserv, class Server, class Client에서 사용 가능해야 함
- 각 Server 클래스와 Client 클래스에, 타입 확인을 위한 static const 추가
    ```static const SocketHandlerType type_ = kServer;```
    ```static const SocketHandlerType type_ = kClient;```

- WebServer::Run() 에서 실행되는 ChangeList() 에 udata 설정하는 구문 추가

**Comment by brixxt27** [comment]
1. 기존의 이벤트 발생시 어떤 소켓에 해당하는지 판별하는 루프문을 제거 => 어느 부분인지 궁금합니다!
2. 타입 확인 용도이고, 확인 시점이 인스턴스 생성 이후라면 static const 가 아닌 const 만 되어도 될 것 같은데 static 이 붙은 다른 이유가 있나요?

**Comment by jwo1024** [comment]
> 1. 기존의 이벤트 발생시 어떤 소켓에 해당하는지 판별하는 루프문을 제거 => 어느 부분인지 궁금합니다!

https://github.com/brixxt27/webserv/blob/9239f5391e345cfecc482d39acf15f42d20cde53/src/modules/Webserv.cpp#L86-L91
이벤트 발생후, 어떤 소켓에서 이벤트가 발생하였는지 확인하는 부분에서 하나하나 current_event의 ident 와 모든 server socket 과 비교해야한다는 오버헤드가 발생합니다.
client socket 의 이벤트가 발생했을 때도 마찬가지로 모든 client socket과 비교를 하게 된다면,  많은 client socket이 존재할수록 오버헤드가 커지겠죠. 

> 2. SocketHandler 역시 어떻게 사용될지 궁금하군요!

그래서 애초에 event 등록시 udata에 해당하는 Server나 Client 클래스의 포인터를 담아두고 사용해보자 했는데,
여기서 Server와 Client 중  어떤 클래스가 담겨있는지 모르는 상황에서 접근해야한다는 문제가 발생합니다.
문제 해결방법으로 같은 타입의 클래스로 묶어 버리자!, SocketHandler라는 클래스를 생성하여 다른 타입 두 클래스에 접근해야겠다 싶었던 거구요.

> 3. 타입 확인 용도이고, 확인 시점이 인스턴스 생성 이후라면 static const 가 아닌 const 만 되어도 될 것 같습니다! static 이 붙은 다른 이유가 있나요?

우선, 위 본문(?)에서는 타입 변수를 Server 와 Client 각각 클래스에 넣고 변하지 않도록 하자는 의미로 써두었는데,
각각의 클래스가아닌 ServerHandler 에 cosnt 타입 변수를 넣고 생성자에서 타입을 지정하는게 좋을것 같네요. const로만  되어도 될 것 같습니다.

**Comment by brixxt27** [comment]
1, 2 번 이해했어요! 아주 좋은 방법이네요👍 형식이나 이름 같이 더 고민해봐요!

**Comment by brixxt27** [comment]
(+추가)
코드 쭉 읽어봤는데 ampersand(&) 가 

1. 레퍼런스로 쓰일 때
2. 주소 연산자로 쓰일 때
3. 비트 연산자로 사용 될 때와 

상관 없이 모두 좌측으로 붙어있는 걸 확인했습니다! 아마 우리가 전부 붙여 버린 적이 있던 것 같은데 그 영향인 것 같아요! 내일 수정해봐요~~
