### ISSUE TITLE
[Bug] Webserv 멤버변수 ```clinets_``` 백터에서 erase 시 컴파일에러 발생

### ISSUE THREAD

**Issue by jwo1024** [brixxt27/webserv#30]
## Describe the bug 

Webserv 클래스의clients_와 servers_를 vetor에서  map으로 변경예정

ManageClientReadEvent() 에서 EOF 발생시, clinet socket의 fd를 닫아주고, 해당 Client 객체를 지워주는 코드를 작성중에 clinet_.erase(); 시 컴파일에러가 발생함이 구조는 for 문으로 clinets_ vector에서 하나하나 어떤 객체에 해당하는지 찾아야 한다는 문제점도 있었고 컴파일 에러도 발생했기 때문에 다른 STL 컨테이너를 고>려해보았습니다. 그 결과 key값만 알고 있으면 지워지는 map 이 적절하겠다고 판단하여 Webserv 클래스에서 가지고 있는 clients_와 servers_를 vector 에서 map으로  수정할 예정입니다.

- 에러위치
https://github.com/brixxt27/webserv/blob/b526ab4aaee0d1949718479db09b161dd7ce5e15/private/jiwolee/build_multiplexing/Webserv.cpp#L129-L139

- 에러 내역

```
jiwoo@ijiuui-MacBookAir build_multiplexing % c++ *.cpp ./Socket/*.cpp
In file included from Webserv.cpp:16:
In file included from ./Webserv.hpp:20:
./Client.hpp:12:7: error: cannot define the implicit copy assignment operator for 'Client', because non-static reference member 'server_' cannot use copy assignment operator
class Client : protected Udata {
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/algorithm:1880:19: note: in implicit copy assignment operator for 'Client' first required here
        *__result = _VSTD::move(*__first);
                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/algorithm:1889:19: note: in instantiation of function template specialization 'std::__move_constexpr<Client *, Client *>' requested here
    return _VSTD::__move_constexpr(__first, __last, __result);
                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/algorithm:1915:19: note: in instantiation of function template specialization 'std::__move<Client *, Client *>' requested here
    return _VSTD::__move(_VSTD::__unwrap_iter(__first), _VSTD::__unwrap_iter(__last), _VSTD::__unwrap_iter(__result));
                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/vector:1718:36: note: in instantiation of function template specialization 'std::move<Client *, Client *>' requested here
    this->__destruct_at_end(_VSTD::move(__p + 1, this->__end_, __p));
                                   ^
Webserv.cpp:133:20: note: in instantiation of member function 'std::vector<Client>::erase' requested here
          clients_.erase(iter);
                   ^
./Client.hpp:22:11: note: declared here
  Server& server_;
          ^
1 error generated.
```

## To do
-
## How to resolve the bug
- Webserv 클래스의clients_와 servers_를 vetor에서  map으로 변경예정

**Comment by brixxt27** [comment]
Webserv 에서 Client를 vector로 가지고 있을 때 생기는 문제점을 두 가지 발견했다.
1. current_event.ident 와 vector 요소 하나씩 비교하여 해당 이벤트가 발생한 vector를 찾아야 하는데 클라이언트가 많을 시 오버헤드가 클 수 있다.
2. recv 가 0을 반환했을 때 client socket 을 close 해주고, Client vector 에서 erase 메소드로 해당 Client 인스턴스를 소멸 시켜줘야 하는데 멤버 변수로 가지고 있는 Server& 때문에 copy assignment operator(등호 연산자) 를 사용하지 못한다. 왜냐하면 vector 는 연속적인 컨테이너로 중간 요소가 지워지면 데이터가 요소별로 연속성을 지속하기 위해 복사해야 하기 때문이다.

이런 오버헤드를 발견하고, Client 자료구조를 map 으로 변경하여 socket 의 fd 를 map 의 key 에 담고, 나머지 정보를 value 에 담는 방식으로 변경할 예정이다.

**Comment by jwo1024** [comment]
https://github.com/brixxt27/webserv/blob/ded7cb99b8968abda62973509adbd7082a43ec71/src/modules/Webserv.hpp#L40

해결하였습니다.
