### ISSUE TITLE
[Feat] Server, Client 와 Udata 가 'is a' 관계가 아니므로 상속을 해제하고 'has a' 관계로 바꾸길 요청

### ISSUE THREAD

**Issue by brixxt27** [brixxt27/webserv#33]
## Description
- Server와 Client 가 Udata 를 상속 받는 형식은 옳지 않다고 생각한다. 상속은 is a 관계가 이상적인데 Server is a Udata 가 아니기 때문이다. 그렇기 때문에 has a 관계로 바꾸어 Udata 객체를 각각 클래스가 갖도록 바꾸길 요청한다.(Server, Client가 Udata를 상속 받는 식이 아닌, Udata를 멤버 변수로 각각 가지고 있는 방식)
- IsServer(), IsClient() 함수를 없애고, Udata 클래스에 private 변수로 서버인지 클라이언트인지 판단할 수 있는 enum 변수를 넣은 후, Udata 객체를 Server 와 Client 가 같도록 하는 것이 옳다고 생각한다. 이는 보다 객체지향적인 설계를 할 수 있도록 할 것이다.
## To do
- [ ] Udata class 재설계
- [ ] 이에 따른 Run() 변경

**Comment by jwo1024** [comment]
Server 와 Client 가 Udata를 상속받게 한 이유는 동일한 형태의 포인터로 kevent의 udata에 넣기 위함이었습니다. 
같은 부모를 상속받게 함으로써 새로운 객체를 생성하지 않고, Server클래스이든 Client 클래스이든 ```*(Udata*)current_event)``` 로 바로 접근이 가능하게 하고싶었습니다.
요청하신말대로 Client 와 Server 가 Udata를 가지고 있는 것은 위의 목적을 달성하지 못합니다.,

이상적인 구조가 아니라는 것에는 동의합니다. 위의 문제를 고려한 또 다른 방법은 없을까요?
